/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.melgust.race;

import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author melgust
 */
public class Main extends javax.swing.JFrame implements Observer {
    
    private final Thread[] threads;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        threads = new Thread[4];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBegin = new javax.swing.JLabel();
        lblEnd = new javax.swing.JLabel();
        txtBegin = new javax.swing.JTextField();
        txtEnd = new javax.swing.JTextField();
        lblInterval = new javax.swing.JLabel();
        lblHorse1 = new javax.swing.JLabel();
        lblHorse2 = new javax.swing.JLabel();
        lblHorse3 = new javax.swing.JLabel();
        lblHorse4 = new javax.swing.JLabel();
        jpbHorse1 = new javax.swing.JProgressBar();
        jpbHorse2 = new javax.swing.JProgressBar();
        jpbHorse3 = new javax.swing.JProgressBar();
        jpbHorse4 = new javax.swing.JProgressBar();
        btnStart = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblWinner = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        lblTimeSeconds = new javax.swing.JLabel();
        lblProgressH1 = new javax.swing.JLabel();
        lblProgressH2 = new javax.swing.JLabel();
        lblProgressH3 = new javax.swing.JLabel();
        lblProgressH4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBegin.setText("Inicio:");

        lblEnd.setText("Fin:");

        txtBegin.setText("1");

        txtEnd.setText("15");

        lblInterval.setText("Intervalo de aumento");

        lblHorse1.setText("Caballo 1");

        lblHorse2.setText("Caballo 2");

        lblHorse3.setText("Caballo 3");

        lblHorse4.setText("Caballo 4");

        btnStart.setText("Iniciar");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnReset.setText("Reiniciar");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblWinner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblWinner.setText("Ganador: Ninguno");

        lblTime.setText("Tiempo retardo:");

        txtTime.setText("1");

        lblTimeSeconds.setText("segundos");

        lblProgressH1.setText("Progreso: 0");

        lblProgressH2.setText("Progreso: 0");

        lblProgressH3.setText("Progreso: 0");

        lblProgressH4.setText("Progreso: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblHorse2)
                                .addGap(18, 18, 18)
                                .addComponent(jpbHorse2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblHorse3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpbHorse3, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblProgressH2)
                                    .addComponent(lblProgressH3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblHorse4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblProgressH4)
                                        .addGap(82, 82, 82)
                                        .addComponent(lblWinner))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnStart)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnReset))
                                        .addComponent(jpbHorse4, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblHorse1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInterval)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBegin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(lblEnd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(lblTime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTimeSeconds))
                            .addComponent(jpbHorse1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProgressH1))
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblHorse1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblInterval)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBegin)
                            .addComponent(lblEnd)
                            .addComponent(txtBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTime)
                            .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTimeSeconds))
                        .addGap(40, 40, 40)
                        .addComponent(jpbHorse1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblHorse2)
                        .addGap(61, 61, 61)
                        .addComponent(lblHorse3)
                        .addGap(59, 59, 59)
                        .addComponent(lblHorse4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblProgressH1)
                        .addGap(23, 23, 23)
                        .addComponent(jpbHorse2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(lblProgressH2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpbHorse3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProgressH3)
                        .addGap(18, 18, 18)
                        .addComponent(jpbHorse4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(lblWinner)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProgressH4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnReset))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        int minimun = Integer.parseInt(this.txtBegin.getText());
        int maximun = Integer.parseInt(this.txtEnd.getText());
        int time = Integer.parseInt(this.txtTime.getText()) * 1000;
        this.btnStart.setEnabled(false);
        this.btnReset.setEnabled(false);
        this.lblWinner.setText("");
        for (int j = 0; j < threads.length; j++) {
            Horse horse = new Horse("Caballo " + (j + 1), minimun, maximun, j + 1, time);
            horse.addObserver(this);
            threads[j] = new Thread(horse);
            threads[j].start();
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        this.jpbHorse1.setValue(0);
        this.lblProgressH1.setText("Progreso: 0");
        this.jpbHorse2.setValue(0);
        this.lblProgressH2.setText("Progreso: 0");
        this.jpbHorse3.setValue(0);
        this.lblProgressH3.setText("Progreso: 0");
        this.jpbHorse4.setValue(0);
        this.lblProgressH4.setText("Progreso: 0");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    private void stop() {
        for (Thread thread : threads) {
            thread.interrupt();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStart;
    private javax.swing.JProgressBar jpbHorse1;
    private javax.swing.JProgressBar jpbHorse2;
    private javax.swing.JProgressBar jpbHorse3;
    private javax.swing.JProgressBar jpbHorse4;
    private javax.swing.JLabel lblBegin;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblHorse1;
    private javax.swing.JLabel lblHorse2;
    private javax.swing.JLabel lblHorse3;
    private javax.swing.JLabel lblHorse4;
    private javax.swing.JLabel lblInterval;
    private javax.swing.JLabel lblProgressH1;
    private javax.swing.JLabel lblProgressH2;
    private javax.swing.JLabel lblProgressH3;
    private javax.swing.JLabel lblProgressH4;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimeSeconds;
    private javax.swing.JLabel lblWinner;
    private javax.swing.JTextField txtBegin;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        Horse horse = (Horse)o;
        int percentage = (int)arg;
        switch(horse.getId()) {
            case 1:
                this.lblProgressH1.setText("Progreso: " + percentage);
                this.jpbHorse1.setValue(percentage);
                break;
            case 2:
                this.lblProgressH2.setText("Progreso: " + percentage);
                this.jpbHorse2.setValue(percentage);
                break;
            case 3:
                this.lblProgressH3.setText("Progreso: " + percentage);
                this.jpbHorse3.setValue(percentage);
                break;
            case 4:
                this.lblProgressH4.setText("Progreso: " + percentage);
                this.jpbHorse4.setValue(percentage);
                break;
        }
        if (percentage >= 100) {
            stop();
            this.btnReset.setEnabled(true);
            this.btnStart.setEnabled(true);
            this.lblWinner.setText("Ganador: " + horse.getName());
        }
    }
}
